import type { Brand } from "@/lib/types";

// Seed brands for the prototype. Rich enough that the workspace feels real;
// added brands (via onboarding) are appended to the client-side store.

export const MOCK_BRANDS: Brand[] = [
  {
    id: "brand-naali",
    name: "Naali",
    slug: "naali",
    website: "https://naali.co",
    category: "Longevity & Wellness",
    primaryMarket: "United States",
    currency: "USD",
    tagline: "Preventive health, designed for women.",
    vibe: "Sophisticated · evidence-led · warm",
    brandColor: "#3F7D6E",
    palette: [
      { hex: "#3F7D6E", role: "primary" },
      { hex: "#E8DFCB", role: "surface" },
      { hex: "#C2785A", role: "accent" },
      { hex: "#2A3B34", role: "ink" },
    ],
    cluster: "Wellness",
    status: "Active",
    onboardingSource: "research",
    enabledSystems: { "brief-generation": true, "static-generation": true, "video-generation": false, "competitor-research": true },
    sections: [
      { id: "naali-s0", sectionType: "identity", sortOrder: 0, title: "Core Identity & Mission", content: "Naali is a women-first longevity platform combining clinically-backed supplementation with a personalized health dashboard. We help women in their 30s–50s invest in healthspan, not just lifespan — reframing wellness from reactive to preventive." },
      { id: "naali-s1", sectionType: "audience", sortOrder: 1, title: "Target Customer Profile", content: "Time-rich, health-curious women 30–55 who treat their health as an asset. They read studies, distrust hype, and respond to credibility over urgency. Primary: 'the optimizer'. Secondary: 'the early-prevention planner' worried about family history." },
      { id: "naali-s2", sectionType: "products", sortOrder: 2, title: "Key Products & Services", content: "Flagship 8-week Biohacking Program; the Daily Longevity Stack; a personalized Health Dashboard app; premium 1:1 coaching tier." },
      { id: "naali-s3", sectionType: "usps", sortOrder: 3, title: "Unique Selling Propositions", content: "Third-party tested formulations; physician-formulated; a quantified dashboard that shows progress; no proprietary blends — full transparency on doses." },
      { id: "naali-s4", sectionType: "voice", sortOrder: 4, title: "Brand Voice & Tone", content: "Calm, intelligent, warm. Speaks peer-to-peer, never condescending or clinical. Leads with mechanism and evidence, lands with reassurance. Avoids exclamation marks and hype adjectives." },
      { id: "naali-s5", sectionType: "visual", sortOrder: 5, title: "Visual Direction", content: "Muted sage + warm sand, generous negative space, editorial serif headlines, soft natural light photography of real women. No stock-photo gloss." },
      { id: "naali-s6", sectionType: "competitors", sortOrder: 6, title: "Competitor Landscape", content: "Competes with Ritual, Seed, and Thorne on transparency; differentiates on the longevity dashboard + women-specific formulation." },
      { id: "naali-s7", sectionType: "constraints", sortOrder: 7, title: "Creative Constraints & Guardrails", content: "No disease-treatment or diagnosis claims (FDA). No before/after body imagery. Always disclose affiliate relationships (FTC). Never imply guaranteed outcomes." },
    ],
    products: [
      { id: "naali-p0", name: "Daily Longevity Stack", category: "Supplement", keyBenefits: "Cellular energy, NAD+ support, antioxidant defense", price: "$68/mo", isHero: true },
      { id: "naali-p1", name: "8-Week Biohacking Program", category: "Program", keyBenefits: "Guided protocol + dashboard + check-ins", price: "$240" },
      { id: "naali-p2", name: "1:1 Longevity Coaching", category: "Service", keyBenefits: "Personalized plan, monthly reviews", price: "$180/mo" },
    ],
    personas: [
      { id: "naali-pe0", name: "The Optimizer", demographics: "F, 34–45, HHI $150k+, urban", psychographics: "Reads PubMed abstracts for fun; tracks sleep + HRV", painPoints: "Overwhelmed by conflicting supplement advice", desires: "A credible, no-BS system she can trust" },
      { id: "naali-pe1", name: "The Prevention Planner", demographics: "F, 44–55, suburban professional", psychographics: "Family history of chronic illness; motivated by control", painPoints: "Fears it's 'too late' to start", desires: "Reassurance that small steps compound" },
    ],
    usps: [
      { id: "naali-u0", text: "Third-party tested, fully transparent doses", category: "Trust", isPrimary: true },
      { id: "naali-u1", text: "A dashboard that quantifies your progress", category: "Product", isPrimary: true },
      { id: "naali-u2", text: "Physician-formulated for women's physiology", category: "Authority" },
    ],
    competitors: [
      { id: "naali-c0", name: "Ritual", websiteUrl: "https://ritual.com", instagramHandle: "@ritual", type: "Direct" },
      { id: "naali-c1", name: "Seed", websiteUrl: "https://seed.com", instagramHandle: "@seed", type: "Direct" },
    ],
    creativeDna: [
      { id: "naali-d0", attributeName: "Tone", value: "Evidence-led, warm, never hype" },
      { id: "naali-d1", attributeName: "Hero color", value: "#3F7D6E sage" },
    ],
    createdAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "brand-aurelia",
    name: "Aurelia Coffee",
    slug: "aurelia-coffee",
    website: "https://aureliacoffee.com",
    category: "Specialty Coffee",
    primaryMarket: "United Kingdom",
    currency: "GBP",
    tagline: "Slow mornings, bright cups.",
    vibe: "Warm · crafted · unhurried",
    brandColor: "#B5562B",
    palette: [
      { hex: "#B5562B", role: "primary" },
      { hex: "#F2E7D5", role: "surface" },
      { hex: "#5A7A64", role: "accent" },
      { hex: "#33241B", role: "ink" },
    ],
    cluster: "Food & Bev",
    status: "Active",
    onboardingSource: "paste",
    enabledSystems: { "brief-generation": true, "static-generation": false, "video-generation": false, "competitor-research": false },
    sections: [
      { id: "aur-s0", sectionType: "identity", sortOrder: 0, title: "Core Identity & Mission", content: "Aurelia is a small-batch specialty roastery that makes single-origin coffee feel unintimidating. We exist to turn the daily cup into a small, deliberate ritual — quality without the snobbery." },
      { id: "aur-s1", sectionType: "audience", sortOrder: 1, title: "Target Customer Profile", content: "Curious home brewers 26–45 who've outgrown supermarket coffee but feel shut out by specialty gatekeeping. They value craft, story, and a friendly hand." },
      { id: "aur-s2", sectionType: "products", sortOrder: 2, title: "Key Products & Services", content: "Rotating single-origin beans; the Discovery subscription; the House Blend; brew kit bundles." },
      { id: "aur-s3", sectionType: "usps", sortOrder: 3, title: "Unique Selling Propositions", content: "Roasted-to-order within 48h; transparent farm-gate pricing; tasting notes written like a friend, not a sommelier; carbon-neutral shipping." },
      { id: "aur-s4", sectionType: "voice", sortOrder: 4, title: "Brand Voice & Tone", content: "Warm, witty, welcoming. Demystifies without dumbing down. Talks about coffee the way a good barista would across the counter." },
      { id: "aur-s5", sectionType: "visual", sortOrder: 5, title: "Visual Direction", content: "Terracotta + cream, hand-drawn marks, grain and warmth, close-up texture shots of beans and pour. Analog, tactile, sunlit." },
      { id: "aur-s6", sectionType: "competitors", sortOrder: 6, title: "Competitor Landscape", content: "Sits between Pact and Origin; differentiates on approachability + the Discovery subscription's storytelling." },
      { id: "aur-s7", sectionType: "constraints", sortOrder: 7, title: "Creative Constraints & Guardrails", content: "No health claims about caffeine. Keep origin claims accurate and sourced. Avoid elitist or gatekeeping language." },
    ],
    products: [
      { id: "aur-p0", name: "Discovery Subscription", category: "Subscription", keyBenefits: "A new single-origin every fortnight + tasting cards", price: "£14/2wk", isHero: true },
      { id: "aur-p1", name: "House Blend", category: "Beans", keyBenefits: "Chocolatey, forgiving, everyday", price: "£9" },
      { id: "aur-p2", name: "Starter Brew Kit", category: "Equipment", keyBenefits: "Everything to brew a great cup at home", price: "£42" },
    ],
    personas: [
      { id: "aur-pe0", name: "The Aspiring Brewer", demographics: "26–38, urban renter", psychographics: "Bought an AeroPress, wants to level up", painPoints: "Specialty feels expensive and confusing", desires: "To make café-quality coffee at home, proudly" },
    ],
    usps: [
      { id: "aur-u0", text: "Roasted to order, shipped within 48 hours", category: "Freshness", isPrimary: true },
      { id: "aur-u1", text: "Tasting notes a human can actually understand", category: "Brand", isPrimary: true },
      { id: "aur-u2", text: "Transparent farm-gate pricing", category: "Ethics" },
    ],
    competitors: [
      { id: "aur-c0", name: "Pact Coffee", websiteUrl: "https://pactcoffee.com", instagramHandle: "@pactcoffee", type: "Direct" },
    ],
    creativeDna: [
      { id: "aur-d0", attributeName: "Tone", value: "Warm, witty, never gatekeeping" },
    ],
    createdAt: "2026-02-03T09:00:00.000Z",
  },
  {
    id: "brand-vespera",
    name: "Vespera",
    slug: "vespera",
    website: "https://vespera.studio",
    category: "Clean Skincare",
    primaryMarket: "Germany",
    currency: "EUR",
    tagline: "Skin rituals for the evening you.",
    vibe: "Quiet luxury · botanical · nocturnal",
    brandColor: "#6E5A86",
    palette: [
      { hex: "#6E5A86", role: "primary" },
      { hex: "#EDE6E0", role: "surface" },
      { hex: "#C2785A", role: "accent" },
      { hex: "#2C2630", role: "ink" },
    ],
    cluster: "Beauty",
    status: "Draft",
    onboardingSource: "wizard",
    enabledSystems: { "brief-generation": true, "static-generation": false, "video-generation": false, "competitor-research": false },
    sections: [
      { id: "ves-s0", sectionType: "identity", sortOrder: 0, title: "Core Identity & Mission", content: "Vespera makes botanical evening skincare that turns winding down into a ritual. Clean, minimalist, and unhurried — the antidote to 12-step routines." },
      { id: "ves-s1", sectionType: "audience", sortOrder: 1, title: "Target Customer Profile", content: "Design-literate women 28–45 who value restraint and ingredient honesty over trend-chasing. They buy fewer, better things." },
      { id: "ves-s2", sectionType: "products", sortOrder: 2, title: "Key Products & Services", content: "Night Serum; Cleansing Balm; the 3-Step Evening Ritual set." },
      { id: "ves-s3", sectionType: "usps", sortOrder: 3, title: "Unique Selling Propositions", content: "Fewer ingredients, all disclosed; refillable glass; fragrance from botanicals only; dermatologist-reviewed." },
      { id: "ves-s4", sectionType: "voice", sortOrder: 4, title: "Brand Voice & Tone", content: "Spare, poetic, calm. Short sentences. Lets white space and ingredients speak. Never shouty." },
      { id: "ves-s5", sectionType: "visual", sortOrder: 5, title: "Visual Direction", content: "Dusk plum + soft stone, candlelit photography, matte glass, lots of shadow. Nocturnal and serene." },
      { id: "ves-s6", sectionType: "competitors", sortOrder: 6, title: "Competitor Landscape", content: "Adjacent to Aesop and Typology; differentiates on the evening-ritual narrative + refill system." },
      { id: "ves-s7", sectionType: "constraints", sortOrder: 7, title: "Creative Constraints & Guardrails", content: "EU cosmetics claim rules — no medical/anti-aging cure claims. Fragrance allergens disclosed. No retouching skin texture." },
    ],
    products: [
      { id: "ves-p0", name: "Night Serum", category: "Skincare", keyBenefits: "Overnight barrier repair, bakuchiol", price: "€54", isHero: true },
      { id: "ves-p1", name: "3-Step Evening Ritual", category: "Set", keyBenefits: "Cleanse, treat, seal", price: "€118" },
    ],
    personas: [
      { id: "ves-pe0", name: "The Minimalist", demographics: "28–45, design/creative fields", psychographics: "Owns fewer, better things; reads ingredient lists", painPoints: "Overwhelmed by overcomplicated routines", desires: "A calm ritual that actually works" },
    ],
    usps: [
      { id: "ves-u0", text: "Fewer ingredients, every one disclosed", category: "Trust", isPrimary: true },
      { id: "ves-u1", text: "Refillable glass — buy the bottle once", category: "Sustainability", isPrimary: true },
    ],
    competitors: [
      { id: "ves-c0", name: "Typology", websiteUrl: "https://typology.com", instagramHandle: "@typology", type: "Direct" },
    ],
    creativeDna: [
      { id: "ves-d0", attributeName: "Tone", value: "Spare, poetic, calm" },
    ],
    createdAt: "2026-03-21T19:30:00.000Z",
  },
];
